version: '3'
services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lamp_docker
      MYSQL_USER: cyx
      MYSQL_PASSWORD: 1411
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  php-apache:
    image: php:8.1-apache
    volumes:
      - "./public:/var/www/html"
    ports:
      - 80:80
      - 443:443

